# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: portfolio.joeypoon.com
title: Joey F. Poon
email: joey@joeypoon.com
author: Joey F. Poon
description: > # "Joey's portfolio site"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/joeyfpoon
  - title: github
    url: https://github.com/joeypoon
  - title: linkedin
    url: https://linkedin.com/in/joeypoon
