url: http://portfolio.joeypoon.com
baseurl: /joeypoon/

# Site settings
title: Joey F. Poon
email: joey@joeypoon.com
description: "Joey's portfolio site"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Joey F. Poon
  pic: 1
  social:
    - title: twitter
      url: http://twitter.com/joeypoon
    - title: linkedin
      url: http://linked.com/in/joeypoon
    - title: github
      url: http://github.com/joeypoon

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/joeypoon
  - title: linkedin
    url: http://linked.com/in/joeypoon
  - title: github
    url: http://github.com/joeypoon

# Postal address (add as many lines as necessary)
# address:
#   - line: 3481 Melrose Place
#   - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
